### ISSUE TITLE
Structure of the data folder and where to download for context and bottles dataset?

### ISSUE THREAD

**Issue by sraghuram90** [DreadPiratePsyopus/Fine_Grained_Clf#1]
Could you update the structure of the data folder and where to download for context and bottles dataset?

**Comment by AndresPMD** [comment]
@sraghuram90 
The data requires the Fisher Vectors obtained from PHOCs which are a textual descriptor of the text contained in an image.
To do so, you can use the following model to extract PHOCs: https://github.com/DreadPiratePsyopus/Pytorch-yolo-phoc or https://github.com/lluisgomez/single-shot-str
And then compute the Fisher Vector out of them.

A link to the datasets can be found in the main Readme guide.

**Comment by zetorange1** [comment]
Hi @DreadPiratePsyopus 
I can't find Embedding file(eg. Drink_Bottle_w2vec.pickle) in dataset.
So I am getting an error when run train.py.
Can you please share full dataset?
Thank you!

**Comment by AndresPMD** [comment]
Hello @ballen127 ,

The datasets were not collected by me, therefore those embeddings are not included there.  
In order to obtain them, you can run an OCR on the dataset and then use one embedding model to embed each word into the desired space (W2Vec, Fasttext, PHOC). An improvement is achieved by using PHOCs + Fisher Vector ( I can provide this features).

**Comment by zetorange1** [comment]
@DreadPiratePsyopus 
I tried to run train.py like this.
`python src/train.py bottles --embedding fisher`

But I am getting this error.
```
Parameters: Namespace(attn=False, batch_size=64, data_path='/SSD/Datasets', dataset='bottles', decay=0.0005, early_stop=10, embedding='fisher', epochs=60, fusion='concat', gamma=0.1, learning_rate=0.001, load=None, log='../results/', log_interval=20, max_textual=15, mmdim=1600, model='baseNet', momentum=0.9, ngpu=1, ocr='e2e_mlt', optim='radam', outimg=False, outimg_path='../visualization/', plot=False, prefetch=4, save='../backup/', save_weights='True', schedule=[15, 30, 45], seed=42, split=2, test='False')
Save dir: ../backup/bottles_baseNet_fisher_e2e_mlt_concat/
Preparing data
Creating Model
Optimizer: radam
Checking CUDA
* CUDA ENABLED!

*** TRAIN ***

Traceback (most recent call last):
File "src/train.py", line 339, in <module>
main()
File "src/train.py", line 289, in main
loss = train(train_loader, net, optim, args.cuda, criterion, epoch, args.log_interval, num_classes, args.batch_size)
File "src/train.py", line 66, in train
for i, (data, labels, textual_features) in enumerate(data_loader):
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
data = self._next_data()
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
return self._process_data(data)
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
data.reraise()
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/white/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/white/Downloads/Fine_Grained_Clf/src/data/bottles.py", line 112, in __getitem__
with open (data_path + relative_path +image_name.replace('images/','')[:-3] +'json')as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/SSD/Datasets/Drink_Bottle/fasttext_fisher/8/948.json'
```

How can I get these drink bottle fisher descriptors?

**Comment by AndresPMD** [comment]
@ballen127 As for now I can provide you with the textual features (PHOC + FV) of the two datasets. I will need an e-mail to send the zipped files since they are too big to keep in some free storage server.
you can write me up at andres {dot) mafla at cvc.uab.es

**Comment by zetorange1** [comment]
@DreadPiratePsyopus I just sent you e-mail.

**Comment by AndresPMD** [comment]
@ballen127 Did you manage to train the model? If so, we can close this thread.

**Comment by leonodelee** [comment]
> @ballen127 As for now I can provide you with the textual features (PHOC + FV) of the two datasets. I will need an e-mail to send the zipped files since they are too big to keep in some free storage server. you can write me up at andres {dot) mafla at cvc.uab.es

I also send you an email, hope to get the PHOC features from you in your convenience.

**Comment by AndresPMD** [comment]
Hey @leonodelee,

As for now I currently do not have that data. However, you can extract it by yourself.

To do so, you can use the following model to extract PHOCs: https://github.com/AndresPMD/Pytorch-yolo-phoc or https://github.com/lluisgomez/single-shot-str.
With the PHOCs obtained of each image, the Fisher Vectors can be obtained and used in this model.

Nonetheless, I invite you to take a look to a better performing approach:

https://github.com/AndresPMD/GCN_classification

**Comment by leonodelee** [comment]
> 

Thank you for your kindful help!
